import "./style.css";
import NewRebillyInstruments from "./instruments";
import RebillyInstruments from "@rebilly/instruments";

document.querySelector<HTMLDivElement>("#app")!.innerHTML = `
  <main>
    <div class="new-rebilly-instruments"></div>
    <hr/>
    <div class="rebilly-instruments"></div>
  </main>
`;

const config = {
  apiMode: "sandbox",
  jwt: "eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJqd3RfMDFKMDZGQVJGVDY5VFhGUTZYU1BWRTRSRjIiLCJleHAiOjE3NDk3NDAzMjYuMzYxNDM5LCJpYXQiOjE3MTgyMDQzMjYuMzk0NjY4LCJhY2wiOlt7InNjb3BlIjp7Im9yZ2FuaXphdGlvbklkIjpbIjBhMjU0MGQyLTIyODUtNDE0ZC1hNjc3LTg2OGJkZTdlNDQyZiJdLCJwYXltZW50TWV0aG9kcyI6WyJJbnRlcmFjLWVUcmFuc2ZlciIsInBheW1lbnQtY2FyZCIsInBheXBhbCJdLCJjdXN0b21GaWVsZE5hbWUiOlsiU0lOTGFzdDQiXX0sInBlcm1pc3Npb25zIjpbMjg0LDI4Niw0MTQsNDE1LDQzNCw0MTEsNDEyLDQyNCw0MjUsNDI2LDQyNyw0MjgsNDI5LDQwOSw0MTAsNDAxLDQwMiw0MzMsNDg4LDQ4Nyw2ODcsNjgxLDY4Nyw2ODEsNjg4XX1dLCJjbGFpbXMiOnsid2Vic2l0ZUlkIjoicG9rZW1vbi5uaW50ZW5kby5jb20iLCJ0cmFuc2FjdGlvbklkIjoidHhuXzAxSjA2RkFSQ0FTQTg5MTM5REFLUVROWTJXIiwicGF5bWVudE1ldGhvZHMiOlsicGF5bWVudC1jYXJkIiwicGF5cGFsIiwiSW50ZXJhYy1lVHJhbnNmZXIiXX0sIm1lcmNoYW50IjoiMGEyNTQwZDItMjI4NS00MTRkLWE2NzctODY4YmRlN2U0NDJmIiwiY3VzdG9tZXIiOnsiaWQiOiJjdXNfMDFIU1ZSOUJCRDRSN1JKQlpROFQ2NVA0UFQiLCJuYW1lIjoiSm9uIEJvYmJ5IiwiY3JlYXRlZFRpbWUiOiIyMDI0LTAzLTI1VDIxOjI5OjI3KzAwOjAwIn19.ZekkOy--09fLWmcLqCqdd0qW-dRTVZvIBkL3TFsl2IWXRU_4WUYYhlSzMbpQ_plq1MjL6sgqNRzLHp_svm9J1erjbcX4_c7S60fAM7gvRzwlqBZglCA6Y5-6YegVc4OfS-JQmCwA8QOdTTn7w8p4gn1eQblO78l_IO0QgoW9xQPV0OjXGXg-4YeVZa6xN__iWBA4i8Albl7kA2seX2MqrSylh45yU1qgi_Edz4gh9h2by8Udb_prnZ-nd7KLxgwIxPHaFDcpX63ttKhIergnzGjTiHRO7URt1wscIJ2cepc5qiH1pNoaSEadrYZj_ODOAygmeRpsna8ZHAkBErJjEg",
};
NewRebillyInstruments.mount(config);

// RebillyInstruments.mount(config);
